---
title: Promise重温理解
date: 2022-06-06
sidebar: true
tags:
 - Promise
categories:
 - JavaScript
 - 面试
---

## 一、关于Promise

Promise是ES6中较为重要的一部分内容，是异步编程绕不开的一项技术，理解起来也不是很容易。为了更深层次理解Promise，不仅仅停留在会用的层次上，就稍微对Promise做一些整理。

Promise 是异步编程的一种解决方案，比传统的解决方案——回调函数和事件，更合理和更强大。它由社区最早提出和实现，ES6 将其写进了语言标准，统一了用法，原生提供了Promise对象。

从语法上说，Promise 是一个对象，里面保存着某个未来才会结束的事件（通常是一个异步操作）的结果，从它可以获取异步操作的消息。Promise 提供统一的 API，各种异步操作都可以用同样的方法进行处理。

Promise也有一些缺点。

- 首先，无法取消Promise，一旦新建它就会立即执行，无法中途取消。
- 其次，如果不设置回调函数，Promise内部抛出的错误不会反应到外部。
- 第三，当处于pending状态时，无法得知目前进展到哪一个阶段（刚刚开始还是即将完成）。

## 二、promise的使用

### 2.1 一个Promise的三种状态

- pending: 初始状态，既不是成功，也不是失败状态，等待判定。
- fulfilled: 意味着操作成功完成。
- rejected: 意味着操作失败

一个pending状态的promise可能会变为fulfilled状态，并传递值给相应的状态处理方法，也可能变为rejected并传递失败信息给相应的状态处理方法。

Promise.prototype.then和Promise.prototype.catch方法返回promise 对象， 所以它们可以被链式调用。

Promise的这三种状态有两个特点：

- 对象的状态不受外界影响。只有异步操作的结果，可以决定当前是哪一种状态，任何其他操作都无法改变这个状态。这也是Promise这个名字的由来，它的英语意思就是“承诺”，表示其他手段无法改变。一旦状态改变，就不会再变，任何时候都可以得到这个结果。
- Promise对象的状态改变，只有两种可能：从pending变为fulfilled和从pending变为rejected。只要这两种情况发生，状态就凝固了，不会再变了，会一直保持这个结果，这时就称为 resolved（已定型）。如果改变已经发生了，你再对Promise对象添加回调函数，也会立即得到这个结果。这与事件（Event）完全不同，事件的特点是，如果你错过了它，再去监听，是得不到结果的。

### 2.2 Promise基本用法

```js
const p = new Promise(function(resolve, reject) {
  // … some code

  If (/* 异步操作成功 */){
    resolve(value);
  } else {
    reject(error);
  }
});
//状态处理
p.then((val)=>{
        console.log(val)
    },(err)=>{
        console.log(err)
    })
```

Promise构造函数接受一个函数作为参数，该函数的两个参数分别是resolve和reject。它们是两个函数，由 JavaScript 引擎提供，不用自己部署。

Resolve函数的作用是，将Promise对象的状态从“未完成”变为“成功”（即从 pending 变为 resolved），在异步操作成功时调用，并将异步操作的结果，作为参数传递出去；

Reject函数的作用是，将Promise对象的状态从“未完成”变为“失败”（即从 pending 变为 rejected），在异步操作失败时调用，并将异步操作报出的错误，作为参数传递出去。

then方法所绑定的即为状态处理方法回调，包含两个参数（两个Function，第一个是fulfilled状态处理，第二个是rejected状态处理），其中，第二个函数是可选的，不一定要提供。这两个函数都接受Promise对象传出的值作为参数。

#### Promise使用例子

```js
function timeout(ms) {
  return new Promise((resolve, reject) => {
    setTimeout(resolve, ms, 'done');//第三个参数作为resolve函数的参数
  });
}

timeout(100).then((value) => {
  console.log(value);
});
//100ms后输出'done'
```

Promise 新建后就会立即执行。

```js
let promise = new Promise(function(resolve, reject) {
  //立即执行，同步代码
  console.log('Promise');
  resolve();
});

promise.then(function() {
  console.log('resolved.');//异步执行
});

console.log('Hi!');//同步代码

// Promise
// Hi!
// resolved
```

#### Promise使用例子2:用Promise包装Ajax

```js
const getJSON = function(url) {
  const promise = new Promise(function(resolve, reject){
    const handler = function() {
      if (this.readyState !== 4) {
        return;
      }
      if (this.status === 200) {
        resolve(this.response);
      } else {
        reject(new Error(this.statusText));
      }
    };
    const client = new XMLHttpRequest();
    client.open("GET", url);
    client.onreadystatechange = handler;
    client.responseType = "json";
    client.setRequestHeader("Accept", "application/json");
    client.send();

  });
  return promise;
};

getJSON("/posts.json").then(function(json) {
  console.log('Contents: ' + json);
}, function(error) {
  console.error('出错了', error);
});
```

### 2.3 Promise使用注意

#### 参数传递

如果调用resolve函数和reject函数时带有参数，那么它们的参数会被传递给回调函数。
reject函数的参数通常是Error对象的实例，表示抛出的错误；
resolve函数的参数除了正常的值以外，还可能是另一个 Promise 实例，比如像下面这样。

```js
const p1 = new Promise(function (resolve, reject) {
  // ...
});
const p2 = new Promise(function (resolve, reject) {
  // ...
  resolve(p1);
})
```

p2的resolve方法将p1作为参数，即一个异步操作的结果是返回另一个异步操作:
这时p1的状态就会传递给p2，也就是说，p1的状态决定了p2的状态。如果p1是pending，那么p2的回调函数就会等待p1的状态改变；如果p1的状态已经是resolved或者rejected，那么p2的回调函数将会立刻执行。

例子：

```js
const p1 = new Promise(function (resolve, reject) {
  setTimeout(() => reject(new Error('fail')), 3000)
})

const p2 = new Promise(function (resolve, reject) {
  setTimeout(() => resolve(p1), 1000)
})

p2
  .then(result => console.log(result))
  .catch(error => console.log(error))
// 3s之后：
// Error: fail

/*解释：
p1是一个 Promise，3 秒之后变为rejected。
p2的状态在 1 秒之后改变，resolve方法返回的是p1。
由于p2返回的是另一个Promise，导致p2自己的状态无效，由p1的状态决定p2的状态。
所以，后面的then语句都变成针对后者（p1）。
又过了 2 秒，p1变为rejected，导致触发catch方法指定的回调函数。
*/
```

#### 参数函数的终结执行

调用resolve或reject并不会终结 Promise 的参数函数的执行

```js
new Promise((resolve, reject) => {
  resolve(1);
  console.log(2);
}).then(r => {
  console.log(r);
});
// 2
// 1
```

使用return会终结执行，一般来说，调用resolve或reject以后，Promise 的使命就完成了，后继操作应该放到then方法里面，而不应该直接写在resolve或reject的后面。所以，最好在它们前面加上return语句。

参数函数内部出现错误也会终结执行，状态改变为rejected，但是不会报错。
